package com.ten.expression;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
@SpringBootApplication
public class ExpressionApplication {

	public static void main(String[] args) {
		SpringApplication.run(ExpressionApplication.class, args);
	}

}
